export const LIST_CANDIDACY = 'LIST_CANDIDACY'
export const LIST_CANDIDACY_PENDING = `${LIST_CANDIDACY}_PENDING`
export const LIST_CANDIDACY_FULFILLED = `${LIST_CANDIDACY}_FULFILLED`
export const LIST_CANDIDACY_REJECTED = `${LIST_CANDIDACY}_REJECTED`

export const RETRIEVE_COUNTER_CANDIDACY = 'RETRIEVE_COUNTER_CANDIDACY'
export const RETRIEVE_COUNTER_CANDIDACY_PENDING = `${RETRIEVE_COUNTER_CANDIDACY}_PENDING`
export const RETRIEVE_COUNTER_CANDIDACY_FULFILLED = `${RETRIEVE_COUNTER_CANDIDACY}_FULFILLED`
export const RETRIEVE_COUNTER_CANDIDACY_REJECTED = `${RETRIEVE_COUNTER_CANDIDACY}_REJECTED`

export const RETRIEVE_CANDIDACY = 'RETRIEVE_CANDIDACY'
export const RETRIEVE_CANDIDACY_PENDING = `${RETRIEVE_CANDIDACY}_PENDING`
export const RETRIEVE_CANDIDACY_FULFILLED = `${RETRIEVE_CANDIDACY}_FULFILLED`
export const RETRIEVE_CANDIDACY_REJECTED = `${RETRIEVE_CANDIDACY}_REJECTED`
