export const LIST_JOB_CANDIDACY_MESSAGE = 'LIST_JOB_CANDIDACY_MESSAGE'
export const LIST_JOB_CANDIDACY_MESSAGE_PENDING = `${LIST_JOB_CANDIDACY_MESSAGE}_PENDING`
export const LIST_JOB_CANDIDACY_MESSAGE_FULFILLED = `${LIST_JOB_CANDIDACY_MESSAGE}_FULFILLED`
export const LIST_JOB_CANDIDACY_MESSAGE_REJECTED = `${LIST_JOB_CANDIDACY_MESSAGE}_REJECTED`
