export const LIST_JOB_CANDIDACY_MESSAGE = 'LIST_JOB_CANDIDACY_MESSAGE'
export const LIST_JOB_CANDIDACY_MESSAGE_PENDING = `${LIST_JOB_CANDIDACY_MESSAGE}_PENDING`
export const LIST_JOB_CANDIDACY_MESSAGE_FULFILLED = `${LIST_JOB_CANDIDACY_MESSAGE}_FULFILLED`
export const LIST_JOB_CANDIDACY_MESSAGE_REJECTED = `${LIST_JOB_CANDIDACY_MESSAGE}_REJECTED`

export const LIST_CANDIDACY_MESSAGE = 'LIST_CANDIDACY_MESSAGE'
export const LIST_CANDIDACY_MESSAGE_PENDING = `${LIST_CANDIDACY_MESSAGE}_PENDING`
export const LIST_CANDIDACY_MESSAGE_FULFILLED = `${LIST_CANDIDACY_MESSAGE}_FULFILLED`
export const LIST_CANDIDACY_MESSAGE_REJECTED = `${LIST_CANDIDACY_MESSAGE}_REJECTED`

export const NEXT_CANDIDACY_MESSAGE = 'NEXT_CANDIDACY_MESSAGE'
export const NEXT_CANDIDACY_MESSAGE_PENDING = `${NEXT_CANDIDACY_MESSAGE}_PENDING`
export const NEXT_CANDIDACY_MESSAGE_FULFILLED = `${NEXT_CANDIDACY_MESSAGE}_FULFILLED`
export const NEXT_CANDIDACY_MESSAGE_REJECTED = `${NEXT_CANDIDACY_MESSAGE}_REJECTED`

export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const CREATE_MESSAGE_PENDING = `${CREATE_MESSAGE}_PENDING`
export const CREATE_MESSAGE_FULFILLED = `${CREATE_MESSAGE}_FULFILLED`
export const CREATE_MESSAGE_REJECTED = `${CREATE_MESSAGE}_REJECTED`
