export const ACTIVATE_USER = 'ACTIVATE_USER'
export const ACTIVATE_USER_PENDING = `${ACTIVATE_USER}_PENDING`
export const ACTIVATE_USER_FULFILLED = `${ACTIVATE_USER}_FULFILLED`
export const ACTIVATE_USER_REJECTED = `${ACTIVATE_USER}_REJECTED`

export const LOGIN_USER = 'LOGIN_USER'

export const RETRIEVE_FROM_TOKEN_USER = 'RETRIEVE_FROM_TOKEN_USER'
export const RETRIEVE_FROM_TOKEN_USER_PENDING = `${RETRIEVE_FROM_TOKEN_USER}_PENDING`
export const RETRIEVE_FROM_TOKEN_USER_FULFILLED = `${RETRIEVE_FROM_TOKEN_USER}_FULFILLED`
export const RETRIEVE_FROM_TOKEN_USER_REJECTED = `${RETRIEVE_FROM_TOKEN_USER}_REJECTED`

export const FORGET_PASSWORD_REQUEST_USER = 'FORGET_PASSWORD_REQUEST_USER'
export const FORGET_PASSWORD_REQUEST_USER_PENDING = `${FORGET_PASSWORD_REQUEST_USER}_PENDING`
export const FORGET_PASSWORD_REQUEST_USER_FULFILLED = `${FORGET_PASSWORD_REQUEST_USER}_FULFILLED`
export const FORGET_PASSWORD_REQUEST_USER_REJECTED = `${FORGET_PASSWORD_REQUEST_USER}_REJECTED`
