export const ACTIVATE_USER = 'ACTIVATE_USER'
export const ACTIVATE_USER_PENDING = `${ACTIVATE_USER}_PENDING`
export const ACTIVATE_USER_FULFILLED = `${ACTIVATE_USER}_FULFILLED`
export const ACTIVATE_USER_REJECTED = `${ACTIVATE_USER}_REJECTED`
