export const CREATE_PRO = 'CREATE_PRO'
export const CREATE_PRO_PENDING = `${CREATE_PRO}_PENDING`
export const CREATE_PRO_FULFILLED = `${CREATE_PRO}_FULFILLED`
export const CREATE_PRO_REJECTED = `${CREATE_PRO}_REJECTED`
