export const LIST_NOTIFICATION = 'LIST_NOTIFICATION'
export const LIST_NOTIFICATION_PENDING = `${LIST_NOTIFICATION}_PENDING`
export const LIST_NOTIFICATION_FULFILLED = `${LIST_NOTIFICATION}_FULFILLED`
export const LIST_NOTIFICATION_REJECTED = `${LIST_NOTIFICATION}_REJECTED`

export const RETRIEVE_COUNTER_NOTIFICATION = 'RETRIEVE_COUNTER_NOTIFICATION'
export const RETRIEVE_COUNTER_NOTIFICATION_PENDING = `${RETRIEVE_COUNTER_NOTIFICATION}_PENDING`
export const RETRIEVE_COUNTER_NOTIFICATION_FULFILLED = `${RETRIEVE_COUNTER_NOTIFICATION}_FULFILLED`
export const RETRIEVE_COUNTER_NOTIFICATION_REJECTED = `${RETRIEVE_COUNTER_NOTIFICATION}_REJECTED`
