export const LIST_JOB = 'LIST_JOB'
export const LIST_JOB_PENDING = `${LIST_JOB}_PENDING`
export const LIST_JOB_FULFILLED = `${LIST_JOB}_FULFILLED`
export const LIST_JOB_REJECTED = `${LIST_JOB}_REJECTED`

export const CREATE_JOB = 'CREATE_JOB'
export const CREATE_JOB_PENDING = `${CREATE_JOB}_PENDING`
export const CREATE_JOB_FULFILLED = `${CREATE_JOB}_FULFILLED`
export const CREATE_JOB_REJECTED = `${CREATE_JOB}_REJECTED`
