export const LIST_JOB = 'LIST_JOB'
export const LIST_JOB_PENDING = `${LIST_JOB}_PENDING`
export const LIST_JOB_FULFILLED = `${LIST_JOB}_FULFILLED`
export const LIST_JOB_REJECTED = `${LIST_JOB}_REJECTED`
